### ISSUE TITLE
bug: Протухает токен, и сам не обновляется в "JWT + JSON file"

### ISSUE THREAD

**Issue by gfh31fgh2** [ydb-platform/ydb-php-sdk#57]
# Bug Report

**YDB PHP SDK version:**
latest

**Environment**
ubuntu18

**Current behavior:**

```
[upsert]: Error, catch: YDB Table BeginTransaction (status code 16): unauthenticated, unauthenticated: { <main>: Error: The token has expired 2023-05-16T19:06:18Z. Now 2023-05-16T19:59:57.983938914Z, which is more than PT10M later }
```

```
PHP Fatal error:  Uncaught YdbPlatform\Ydb\Exception: YDB Table DeleteSession (status code 16): unauthenticated, unauthenticated: { <main>: Error: The token has expired 2023-05-16T17:42:03Z. Now 2023-05-16T18:09:58.186074496Z, which is more than PT10M later } in /home/path/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php:161
#012Stack trace:
#012#0 /home/path/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php(85): YdbPlatform\Ydb\Session->checkStatus('Table', 'DeleteSession', Object(stdClass))
#012#1 /home/path/vendor/ydb-platform/ydb-php-sdk/src/Session.php(600): YdbPlatform\Ydb\Session->doRequest('Table', 'DeleteSession', Array)
#012#2 /home/path/vendor/ydb-platform/ydb-php-sdk/src/Session.php(151): YdbPlatform\Ydb\Session->request('DeleteSession', Array)
#012#3 /home/path/vendor/ydb-platform/ydb-php-sdk/src/Sessions/MemorySessionPool.php(23): YdbPlatform\Ydb\Session->delete()
#012#4 [internal function]: YdbPlatform\Ydb\Sessions\MemorySessionPool->__destruct()
#012#5 {main}
#012  thrown in /home/path/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php on line 161
```

**Expected behavior:**

php working more than 12 hours

**Steps to reproduce:**

php in background with simple select from ydb

**Related code:**

https://github.com/gfh31fgh2/ydb-php-simple-driver

**Comment by gfh31fgh2** [comment]
[upsert]: Error, catch: YDB Table BeginTransaction (status code 16): unauthenticated, unauthenticated: { <main>: Error: The token has expired 2023-05-16T19:06:18Z. Now 2023-05-16T19:59:57.983938914Z, which is more than PT10M later }

**Comment by gfh31fgh2** [comment]
все работает, спасибо!
