### ISSUE TITLE
bug: fatal SDK with disconnect

### ISSUE THREAD

**Issue by gfh31fgh2** [ydb-platform/ydb-php-sdk#61]
# Bug Report

**YDB PHP SDK version:**
latest

**Environment**
ubuntu18

**Current behavior:**

```
PHP Fatal error:  Uncaught YdbPlatform\Ydb\Exception: YDB Table DeleteSession (status code 14): failed to connect to all addresses; last error: 
UNKNOWN: ipv4:xx.xxx.xxx.xx:2135: tcp handshaker shutdown in /path/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php:163#012
Stack trace:
#012#0 /path/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php(87): YdbPlatform\Ydb\Session->checkStatus('Table', 'DeleteSession', Object(stdClass))
#012#1 /path/vendor/ydb-platform/ydb-php-sdk/src/Session.php(604): YdbPlatform\Ydb\Session->doRequest('Table', 'DeleteSession', Array)
#012#2 /path/vendor/ydb-platform/ydb-php-sdk/src/Session.php(152): YdbPlatform\Ydb\Session->request('DeleteSession', Array)
#012#3 /path/vendor/ydb-platform/ydb-php-sdk/src/Sessions/MemorySessionPool.php(23): YdbPlatform\Ydb\Session->delete()
#012#4 [internal function]: YdbPlatform\Ydb\Sessions\MemorySessionPool->__destruct()
#012#5 {main}#012  thrown in /path/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php on line 163

```

**Expected behavior:**

php working more than 12 hours
and somehow we lost internet connection

**Steps to reproduce:**

php in background with simple select from ydb  and disconnect 

**Related code:**

https://github.com/gfh31fgh2/ydb-php-simple-driver

**Comment by rekby** [comment]
Hello, thanks for the report.

It is "Unavailable" error from grpc library. SDK must retry, but don't do that.

**Comment by rekby** [comment]
Да, это возможно - php может ловить grpc-ошибки и может ретраить собственные обращения к серверу.

Со стороны grpc-библиотеки проблемы нет.

**Comment by dudev** [comment]
Похоже, этот баг уже пофикшен. Конкретный краш из репорта — необработанное исключение в `MemorySessionPool::__destruct()` при падении `Session::delete()` с `UNAVAILABLE` — был закрыт коммитом 78af75c в июне 2023, через месяц после этого репорта: деструктор оборачивает `delete()` в ретрай и ловит итоговое исключение. Этот коммит есть во всех релизах начиная с v1.6.0. Плюс в SDK давно есть общая инфраструктура ретраев (`Retry`, `Table::retryTransaction()`/`Ydb::retryTransaction()`) для клиентского кода. Вероятно, эту задачу стоит закрыть

**Comment by gfh31fgh2** [comment]
Ну с 26 мая 2023 года уже прошло 3 года. Быстро вы конечно

> Похоже, этот баг уже пофикшен. Конкретный краш из репорта — необработанное исключение в `MemorySessionPool::__destruct()` при падении `Session::delete()` с `UNAVAILABLE` — был закрыт коммитом [78af75c](https://github.com/ydb-platform/ydb-php-sdk/commit/78af75c42dd4a6ce4ce69151d14d754d1ded8d9c) в июне 2023, через месяц после этого репорта: деструктор оборачивает `delete()` в ретрай и ловит итоговое исключение. Этот коммит есть во всех релизах начиная с v1.6.0. Плюс в SDK давно есть общая инфраструктура ретраев (`Retry`, `Table::retryTransaction()`/`Ydb::retryTransaction()`) для клиентского кода. Вероятно, эту задачу стоит закрыть
