### ISSUE TITLE
bug: 401 error in obtain  new iamToken

### ISSUE THREAD

**Issue by gfh31fgh2** [ydb-platform/ydb-php-sdk#64]
# Bug Report

**YDB PHP SDK version:**
latest

**Environment**
ubuntu18

**Current behavior:**

```

PHP Fatal error:  Uncaught YdbPlatform\Ydb\Exception: Failed to obtain new iamToken: response status is 401 in 
/path/vendor/ydb-platform/ydb-php-sdk/src/Iam.php:155#012

Stack trace:
#012#0 /path/vendor/ydb-platform/ydb-php-sdk/src/Iam.php(407): YdbPlatform\Ydb\Iam->newToken()
#012#1 /path/vendor/ydb-platform/ydb-php-sdk/src/Iam.php(79): YdbPlatform\Ydb\Iam->loadToken()
#012#2 /path/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php(44): YdbPlatform\Ydb\Iam->token()
#012#3 /path/vendor/ydb-platform/ydb-php-sdk/src/Session.php(604): YdbPlatform\Ydb\Session->doRequest('Table', 'DeleteSession', Array)
#012#4 /path/vendor/ydb-platform/ydb-php-sdk/src/Session.php(152): YdbPlatform\Ydb\Session->request('DeleteSession', Array)
#012#5 /path/vendor/ydb-platform/ydb-php-sdk/src/Sessions/MemorySessionPool.php(23): YdbPlatform\Ydb\Session->delete()
#012#6 [internal function]: YdbPlatform\Ydb\Sessions\MemorySessionPool->__destruct()
#012#7 {main}
#012  thrown in /path/vendor/ydb-platform/ydb-php-sdk/src/Iam.php on line 155

```

**Expected behavior:**

php working more than 12 hours

**Steps to reproduce:**

php in background with simple select from ydb 

**Related code:**

https://github.com/gfh31fgh2/ydb-php-simple-driver

**Comment by gfh31fgh2** [comment]
1.5.0 - та же ошибка
1.5.1 - та же ошибка
1.5.3 - та же ошибка

**Comment by rekby** [comment]
Ошибку с выписванием JWT-токена поправили, проверьте пожалуйста версию 1.5.4

**Comment by gfh31fgh2** [comment]
не работает

PHP Version 7.4.30

ошибка:
`production.ERROR: Return value of YdbPlatform\Ydb\Auth\IamAuth::requestToken() must be an instance of YdbPlatform\Ydb\Auth\mixed, instance of stdClass returned {"userId":1,"exception":"[object] (TypeError(code: 0): Return value of YdbPlatform\\Ydb\\Auth\\IamAuth::requestToken() must be an instance of YdbPlatform\\Ydb\\Auth\\mixed, instance of stdClass returned at /path/releases/2023.06.03_10-01-19.ea0b574/vendor/ydb-platform/ydb-php-sdk/src/Auth/IamAuth.php:4`

**Comment by gfh31fgh2** [comment]
этот баг-репорт не closed должен быть

**Comment by gfh31fgh2** [comment]
все работает, спасибо!
