### ISSUE TITLE
bug: YDB Table DeleteSession (status code 14): failed to connect to all addresses;

### ISSUE THREAD

**Issue by gfh31fgh2** [ydb-platform/ydb-php-sdk#81]
# Bug Report

**YDB PHP SDK version:**
latest (1.5.6)

**Environment**
ubuntu18 and JWT
php7.2

**Current behavior:**
Используется код, который в related code.

Проблема: Перестало работать

`
PHP Fatal error:  Uncaught YdbPlatform\Ydb\Exception: YDB Table DeleteSession (status code 14): failed to connect to all addresses; last error: UNKNOWN: ipv4:84.201.151.183:2135: tcp handshaker shutdown in 
/path/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php:163
#012
Stack trace:
#012#0 /path/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php(87): YdbPlatform\Ydb\Session->checkStatus('Table', 'DeleteSession', Object(stdClass))
#012#1 /home/cdasrv1/v2/vendor/ydb-platform/ydb-php-sdk/src/Session.php(599): YdbPlatform\Ydb\Session->doRequest('Table', 'DeleteSession', Array)
#012#2 /path/vendor/ydb-platform/ydb-php-sdk/src/Session.php(152): YdbPlatform\Ydb\Session->request('DeleteSession', Array)
#012#3 /path/vendor/ydb-platform/ydb-php-sdk/src/Sessions/MemorySessionPool.php(23): YdbPlatform\Ydb\Session->delete()
#012#4 [internal function]: YdbPlatform\Ydb\Sessions\MemorySessionPool->__destruct()
#012#5 {main}
#012  thrown in /home/cdasrv1/v2/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php on line 163
`

**Expected behavior:**

Без fatalov

**Related code:**

https://github.com/gfh31fgh2/ydb-php-simple-driver

**Comment by gfh31fgh2** [comment]
Также ошибки. Сервера в облаке яндекса таких ошибок не имеют.
`
 YDB Table CreateSession (status code 14): failed to connect to all addresses; last error: UNKNOWN: ipv4:84.201.151.183:2135: tcp handshaker shutdown
`
