### ISSUE TITLE
bug: BadSessionException

### ISSUE THREAD

**Issue by gfh31fgh2** [ydb-platform/ydb-php-sdk#94]
# Bug Report

**YDB PHP SDK version:**
1.8.1

**Environment**
ubuntu18
JWT

**Current behavior:**

```
 PHP Fatal error:  Uncaught Error: Class 'YdbPlatform\Ydb\Exceptions\Ydb\BadSessionException' not found in /path/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php:259#012Stack trace:#012#0 /path/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php(100): YdbPlatform\Ydb\Session->processResponse('Table', 'BeginTransactio...', Object(Ydb\Operations\Operation), '\\Ydb\\Table\\Begi...')#012#1 /path/vendor/ydb-platform/ydb-php-sdk/src/Session.php(601): YdbPlatform\Ydb\Session->doRequest('Table', 'BeginTransactio...', Array)#012#2 /path/vendor/ydb-platform/ydb-php-sdk/src/Session.php(231): YdbPlatform\Ydb\Session->request('BeginTransactio...', Array)#012#3 /path/vendor/ydb-platform/ydb-php-sdk/src/Table.php(488): YdbPlatform\Ydb\Session->beginTransaction()#012#4 /path/vendor/ydb-platform/ydb-php-sdk/src/Table.php(473): YdbPlatform\Ydb\Table->YdbPlatform\Ydb\{closure}(Object(YdbPlatform\Ydb\Session))#012#5 /path/vendor/ydb-platform/ydb-php-sdk/src/Retry/Retry.php( in /path/vendor/ydb-platform/ydb-php-sdk/src/Traits/RequestTrait.php on line 259

```

**Expected behavior:**

php working more than 12 hours

**Steps to reproduce:**

php working more than 12 hours

**Related code:**

https://github.com/gfh31fgh2/ydb-php-simple-driver

**Comment by rekby** [comment]
Can't reproduce the problem.

If is is actual - need full reproduce scenario from scratch environment (ideal - from empty ubuntu docker container).
